// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetOopsUserOKCode is the HTTP code returned for type GetOopsUserOK
const GetOopsUserOKCode int = 200

/*GetOopsUserOK Returns the greeting.

swagger:response getOopsUserOK
*/
type GetOopsUserOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetOopsUserOK creates GetOopsUserOK with default headers values
func NewGetOopsUserOK() *GetOopsUserOK {

	return &GetOopsUserOK{}
}

// WithPayload adds the payload to the get oops user o k response
func (o *GetOopsUserOK) WithPayload(payload string) *GetOopsUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get oops user o k response
func (o *GetOopsUserOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOopsUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetOopsUserBadRequestCode is the HTTP code returned for type GetOopsUserBadRequest
const GetOopsUserBadRequestCode int = 400

/*GetOopsUserBadRequest Invalid characters in "user" were provided.

swagger:response getOopsUserBadRequest
*/
type GetOopsUserBadRequest struct {
}

// NewGetOopsUserBadRequest creates GetOopsUserBadRequest with default headers values
func NewGetOopsUserBadRequest() *GetOopsUserBadRequest {

	return &GetOopsUserBadRequest{}
}

// WriteResponse to the client
func (o *GetOopsUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
