// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetOopsUserHandlerFunc turns a function with the right signature into a get oops user handler
type GetOopsUserHandlerFunc func(GetOopsUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOopsUserHandlerFunc) Handle(params GetOopsUserParams) middleware.Responder {
	return fn(params)
}

// GetOopsUserHandler interface for that can handle valid get oops user params
type GetOopsUserHandler interface {
	Handle(GetOopsUserParams) middleware.Responder
}

// NewGetOopsUser creates a new http.Handler for the get oops user operation
func NewGetOopsUser(ctx *middleware.Context, handler GetOopsUserHandler) *GetOopsUser {
	return &GetOopsUser{Context: ctx, Handler: handler}
}

/*GetOopsUser swagger:route GET /oops/{user} getOopsUser

Returns a greeting to the user!

*/
type GetOopsUser struct {
	Context *middleware.Context
	Handler GetOopsUserHandler
}

func (o *GetOopsUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOopsUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
